name: Snake Animation

on:
  schedule:
    # Execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write  # Permissão para fazer push de alterações

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      # Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: Carloshenriqueapi
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
